services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_chatbot
    environment:
      - PYTHONPATH=/app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - ./.env
<<<<<<< HEAD
=======
    networks:
      - hana-network
    depends_on:
      - rasa

  rasa:
    image: rasa/rasa:3.6.15-full
    container_name: rasa_server
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app
    command: run --enable-api --cors "*" --model models
    networks:
      - hana-network
    depends_on:
      - action_server

  action_server:
    image: rasa/rasa-sdk:3.6.2
    container_name: rasa_action_server
    ports:
      - "5055:5055"
    user: root
    volumes:
      - ./rasa/actions:/app/actions
    entrypoint: []
    command: sh -c "pip install requests && python -m rasa_sdk --actions actions"
    networks:
      - hana-network
>>>>>>> LLM

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    env_file:
      - ./.env
    command:
      - "http"
      - "app:5000"
    networks:
      - hana-network
    depends_on:
      - app

networks:
  hana-network:
    driver: bridge
